node {
	stage("checkout") {
		deleteDir()
		checkout scm
	}

	stage("build") {
		sh "./gradlew assemble"
	}

	stage("test") {
		sh "./gradlew test"
		junit 'build/**/TEST-*.xml'
	}

	stage("publish") {
		archiveArtifacts "build/libs/*.jar"
	}
}